name: Plugins Release

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository to pull the source code
      - uses: actions/checkout@v4

      # Set up Node.js and specify the version
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org

      # Install dependencies
      - run: yarn          

      # Build the project (this step replaces the separate build job)
      - run: yarn nx run plugins:build --verbose --skip-nx-cache
      # Add these steps to your workflow for debugging
      - name: Check directory structure
        run: ls -R ./dist/packages/plugins
        
      - name: Check npm config
        run: npm config list
        
      - run: cd ./dist/packages/plugins && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  create-github-release:
    needs: publish-npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Get Version from package.json
        id: get_version
        run: echo "VERSION=$(node -p 'require("./packages/plugins/package.json").version')" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: "v${{ steps.get_version.outputs.VERSION }}"
          release_name: "v${{ steps.get_version.outputs.VERSION }}"
          draft: false
          prerelease: false
